services:
        pretrain:
                image: nuneslu/contrastive_scene_context:latest
                runtime: nvidia
                environment:
                      - NVIDIA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
                      - OUT_DIR=/home/ContrastiveSceneContexts/pretrain/contrastive_scene_contexts/output
                      - DATASET=/home/ContrastiveSceneContexts/Datasets/PointContrastSemKITTI
                volumes: 
                      - $PWD:/home/ContrastiveSceneContexts
                      - $PWD/Datasets/:/home/ContrastiveSceneContexts/Datasets

